---
- hosts: LinuxUbuntu
  become: true
  become_method: sudo
  become_user: root

  tasks:
    - name: Zeige aktuellen Benutzer (ohne sudo)
      command: whoami
      register: whoami_normal

    - name: Ausgabe ohne sudo
      debug:
        msg: "Vor sudo: {{ whoami_normal.stdout }}"

    - name: Zeige aktuellen Benutzer (mit sudo)
      become: true
      command: whoami
      register: whoami_sudo

    - name: Ausgabe mit sudo
      debug:
        msg: "Nach sudo: {{ whoami_sudo.stdout }}"

    - name: Test ob apt funktioniert (ohne Änderung)
      become: true
      shell: apt-get -v | head -n 1
      register: apt_test
      ignore_errors: true

    - name: Ergebnis des apt Tests
      debug:
        msg: "APT-Test: {{ apt_test.stdout | default('Fehler beim Zugriff auf apt') }}"
