---
- hosts: LinuxUbuntu
  become: true
  become_method: sudo
  become_user: root

  vars:
    timestamp_safe: "{{ (ansible_date_time.date ~ '_' ~ ansible_date_time.time) | regex_replace(':','') }}"
    log_diff: "/var/log/config_diffs_{{ timestamp_safe }}.txt"
    log_list: "/var/log/config_changes_{{ timestamp_safe }}.txt"
    log_diag: "/var/log/apt_diagnose_{{ timestamp_safe }}.log"
    backup_dir: "/var/backups/apt_config_{{ timestamp_safe }}"
    critical_paths:
      - "/etc/ssh"
      - "/etc/network"
      - "/etc/netplan"
      - "/etc/hosts"
      - "/etc/hostname"

  tasks:
    - name: Initialisiere Variablen
      set_fact:
        critical_files: []

    # ------------------------------------------------------------
    # Lock-Prüfung
    # ------------------------------------------------------------
    - name: Prüfe und warte auf freie APT-/DPKG-Locks
      shell: |
        for LOCK in /var/lib/dpkg/lock /var/lib/dpkg/lock-frontend /var/lib/apt/lists/lock; do
          if [ -e "$LOCK" ]; then
            if fuser "$LOCK" >/dev/null 2>&1; then
              echo "APT-Lock aktiv auf $LOCK – warte..."
              ATTEMPTS=0
              while [ "$ATTEMPTS" -lt 30 ]; do
                sleep 10
                if ! fuser "$LOCK" >/dev/null 2>&1; then
                  echo "$LOCK wurde freigegeben"
                  break
                fi
                ATTEMPTS=$((ATTEMPTS+1))
              done
              if [ "$ATTEMPTS" -eq 30 ]; then
                echo "Timeout: Lock $LOCK nach 5 Minuten immer noch aktiv."
                exit 1
              fi
            else
              echo "Kein Prozess für $LOCK gefunden – entferne verwaiste Lock-Datei."
              rm -f "$LOCK"
            fi
          fi
        done
      register: lock_check
      changed_when: false
      failed_when: lock_check.rc != 0

    # ------------------------------------------------------------
    # Paketquellen und Updates
    # ------------------------------------------------------------
    - name: Stelle sicher, dass psmisc (fuser) vorhanden ist
      apt:
        name: psmisc
        state: present
        update_cache: false

    - name: Paketquellen aktualisieren (mit Fehlerbehandlung)
      shell: |
        apt-get update -o Acquire::Retries=2 -o Acquire::http::Timeout=20 -o Acquire::https::Timeout=20 2>&1
      register: update_result
      changed_when: "'Paketlisten werden gelesen' in update_result.stdout"
      failed_when: false

    - name: Upgrade ausführen (bestehende Konfigurationen behalten)
      apt:
        upgrade: yes
        force_apt_get: yes
        dpkg_options:
          - "--force-confdef"
          - "--force-confold"
      register: upgrade_result
      failed_when: false

    # ------------------------------------------------------------
    # Diagnose-Logs
    # ------------------------------------------------------------
    - name: "Fehlerdiagnose: Prüfe auf APT/GPG-Probleme"
      shell: |
        apt-get update -o Acquire::Retries=2 -o Acquire::http::Timeout=15 -o Acquire::https::Timeout=15 2>&1 | tee "{{ log_diag }}"
      register: apt_diag
      changed_when: false
      failed_when: false

    - name: Analyse der Diagnoseausgabe
      set_fact:
        apt_summary: |
          {% set out = [] %}
          {% for line in apt_diag.stdout_lines %}
            {% if 'Fehl' in line or 'ungültig' in line or 'nicht unterstützt' in line %}
              {% set _ = out.append(line) %}
            {% endif %}
          {% endfor %}
          {% if out | length == 0 %}
            ✅ Keine Probleme gefunden
          {% else %}
            ⚠️  {{ out | join('\n⚠️  ') }}
          {% endif %}

    - name: Zusammenfassung für diesen Host anzeigen
      debug:
        msg: |
          ===== APT-Diagnose-Zusammenfassung =====
          [{{ inventory_hostname }}]
          {{ apt_summary }}

    # ------------------------------------------------------------
    # Nach neuen/alten Konfigurationsdateien suchen
    # ------------------------------------------------------------
    - name: Nach neuen/alten Konfigurationsdateien suchen
      find:
        paths: "{{ critical_paths + ['/etc'] | unique }}"
        file_type: file
        patterns:
          - "*.dpkg-new"
          - "*.dpkg-dist"
          - "*.ucf-old"
      register: new_configs
      changed_when: false
      failed_when: false

    - name: Verzeichnisse für Backups/Logs anlegen
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop:
        - "{{ backup_dir }}"
        - "{{ log_diff | dirname }}"
      changed_when: false

    - name: Header für Diff-Log anlegen
      when: new_configs.matched | int > 0
      copy:
        dest: "{{ log_diff }}"
        content: |
          Vergleich neuer Konfigurationsdateien – {{ ansible_date_time.iso8601 }}
          ------------------------------------------------------------
        owner: root
        group: root
        mode: '0644'

    - name: Header für Liste der neuen Konfigurationsdateien anlegen
      when: new_configs.matched | int > 0
      copy:
        dest: "{{ log_list }}"
        content: |
          Upgrade-Datum: {{ ansible_date_time.iso8601 }}
          ------------------------------------------------------------
        owner: root
        group: root
        mode: '0644'

    - name: Neue Dateien sichern
      copy:
        src: "{{ item.path }}"
        dest: "{{ backup_dir }}/new__{{ item.path | regex_replace('^/','') | regex_replace('/','_') }}"
        owner: root
        group: root
        mode: '0644'
        remote_src: true
      loop: "{{ new_configs.files | default([]) }}"
      when: new_configs.matched | int > 0

    - name: Prüfe, ob Originaldateien existieren
      stat:
        path: "{{ item.path | regex_replace('\\.dpkg-new$','') | regex_replace('\\.dpkg-dist$','') | regex_replace('\\.ucf-old$','') }}"
      loop: "{{ new_configs.files | default([]) }}"
      register: orig_stat_list
      when: new_configs.matched | int > 0

    - name: Originaldateien sichern (falls vorhanden)
      copy:
        src: "{{ item.item.path | regex_replace('\\.dpkg-new$','') | regex_replace('\\.dpkg-dist$','') | regex_replace('\\.ucf-old$','') }}"
        dest: "{{ backup_dir }}/orig__{{ item.item.path | regex_replace('^/','') | regex_replace('/','_') }}"
        owner: root
        group: root
        mode: '0644'
        remote_src: true
      loop: "{{ orig_stat_list.results | selectattr('stat.exists', 'defined') | selectattr('stat.exists') | list }}"
      when: new_configs.matched | int > 0

    # ------------------------------------------------------------
    # Abschluss / Übersicht
    # ------------------------------------------------------------
    - name: APT-Update-Ergebnis anzeigen
      debug:
        var: update_result.stdout_lines

    - name: APT-Upgrade-Ergebnis anzeigen
      debug:
        var: upgrade_result.stdout_lines
