---
- hosts: LinuxUbuntu
  become: true
  tasks:
    - name: Paketlisten aktualisieren
      apt:
        update_cache: yes
      register: update_result

    - name: Upgrade mit Sicherung neuer Konfigurationsdateien
      shell: |
        DEBIAN_FRONTEND=noninteractive \
        apt-get -o Dpkg::Options::="--force-confdef" \
                -o Dpkg::Options::="--force-confnew" \
                upgrade -y
      register: upgrade_result

    - name: Nach neuen oder geänderten Konfigurationsdateien suchen
      shell: |
        find /etc -type f \( -name "*.dpkg-new" -o -name "*.dpkg-dist" -o -name "*.ucf-old" \) 2>/dev/null
      register: new_configs
      changed_when: false
      failed_when: false

    - name: Liste der neuen Konfigurationen anzeigen
      debug:
        msg: "{{ new_configs.stdout_lines | default(['Keine neuen Konfigurationsdateien gefunden']) }}"

    - name: Liste der neuen Konfigurationen sichern
      copy:
        dest: "/var/log/config_changes_{{ ansible_date_time.date }}_{{ ansible_date_time.time }}.txt"
        content: |
          Upgrade-Datum: {{ ansible_date_time.iso8601 }}
          ------------------------------------------------------------
          {% if new_configs.stdout_lines %}
          {% for line in new_configs.stdout_lines %}
          {{ line }}
          {% endfor %}
          {% else %}
          Keine neuen oder geänderten Konfigurationsdateien gefunden.
          {% endif %}
      when: new_configs.stdout_lines | length > 0
