---
# Playbook: apt_update.yml
# Zweck: sicheres APT Update + Upgrade mit der Rolle apt_safe_upgrade

- hosts: LinuxUbuntu
  become: true
  become_method: sudo
  become_user: root

  roles:
    - apt_safe_upgrade
