---
- name: Upgrade Linux Pakete ohne Config-Überschreibung
  hosts: all
  become: yes
  gather_facts: false

  vars:
    run_id: "RUN-{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all packages but never overwrite config files
      ansible.builtin.apt:
        upgrade: dist
        dpkg_options: "force-confdef,force-confold"

    - name: Search for .dpkg-dist files
      ansible.builtin.find:
        paths: /etc
        patterns: "*.dpkg-dist"
        recurse: yes
      register: dpkg_dist_files

    - name: Collect results for central log
      ansible.builtin.set_fact:
        dpkg_dist_report: "{{ dpkg_dist_files.files | map(attribute='path') | list }}"
    
    - name: Add report to run-wide variable
      ansible.builtin.set_fact:
        central_dpkg_report: "{{ hostvars | dict2items | selectattr('value.dpkg_dist_report','defined') | items2dict(key_name='key', value_name='value.dpkg_dist_report') }}"
      run_once: true
      delegate_to: localhost

- name: Write central log + summary
  hosts: localhost
  gather_facts: false

  vars:
    run_id: "{{ hostvars | dict2items | map(attribute='value.run_id') | first }}"

  tasks:
    - name: Get current timestamp
      ansible.builtin.command: date "+%Y-%m-%d %H:%M:%S"
      register: current_time
      changed_when: false

    - name: Write dpkg-dist findings to central log
      ansible.builtin.lineinfile:
        path: /var/log/ansible-dpkg-dist.log
        create: yes
        line: "{{ run_id }} {{ current_time.stdout }} {{ item.0 }}: {{ item.1 }}"
      loop: >-
        {{
          hostvars.localhost.central_dpkg_report | dict2items |
          subelements('value')
        }}
      when: item.1 is defined

    - name: Summary output
      ansible.builtin.debug:
        msg: >-
          Run {{ run_id }} abgeschlossen.
          Es wurden {{ hostvars.localhost.central_dpkg_report | dict2items | map('length', attribute='value') | sum }} neue .dpkg-dist Dateien gefunden.

    - name: Diff Hinweise ausgeben
      ansible.builtin.debug:
        msg: "Vergleich auf {{ item.0 }}: diff -u {{ item.1 | regex_replace('\\.dpkg-dist$', '') }} {{ item.1 }}"
      loop: >-
        {{
          hostvars.localhost.central_dpkg_report | dict2items |
          subelements('value')
        }}
      when: item.1 is defined

    - name: Email report senden
      community.general.mail:
        host: localhost
        port: 25
        subject: "[Ansible] .dpkg-dist Report {{ run_id }}"
        to: admin@example.com
        from: ansible@example.com
        body: |
          Run-ID: {{ run_id }}
          Zeitpunkt: {{ current_time.stdout }}

          Gefundene .dpkg-dist Dateien:

          {% for host, files in hostvars.localhost.central_dpkg_report.items() %}
          Host {{ host }}:
          {% for f in files %}
            - {{ f }}
          {% endfor %}
          {% endfor %}
      when: hostvars.localhost.central_dpkg_report | length > 0
